name: Run main.py 

on:
 push:  # Trigger on every commit
    branches:
      - Shreyas-bellary-patch-1

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v3
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12' 

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Execute main.py
        run: python main.py

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || git commit -m "Updated CSV" --allow-empty

      - name: Push changes
        uses: ad-m/github-push-action@v1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch : Shreyas-bellary-patch-1
